export interface ServiceCategory {
  id: string
  label: string
  serpQuery: string
  localSerpQuery?: string
  awinCategory?: string
  serviceType: 'local' | 'remote' | 'both'
  freetrustCategoryId: string
  icon: string
}

export const SERVICE_CATEGORIES: ServiceCategory[] = [
  {
    id: 'accounting-finance',
    label: 'Accounting & Finance',
    serpQuery: 'accounting bookkeeping financial services',
    localSerpQuery: 'accountants bookkeepers financial advisors',
    awinCategory: 'financial-services',
    serviceType: 'both',
    freetrustCategoryId: 'finance-accounting',
    icon: '📊',
  },
  {
    id: 'beauty-wellness',
    label: 'Beauty & Wellness',
    serpQuery: 'beauty salon spa wellness therapist services',
    serviceType: 'local',
    freetrustCategoryId: 'beauty-personal-care',
    icon: '💆',
  },
  {
    id: 'business-consulting',
    label: 'Business Consulting',
    serpQuery: 'business consulting strategy advisory services',
    localSerpQuery: 'business consultants advisors',
    awinCategory: 'business-services',
    serviceType: 'both',
    freetrustCategoryId: 'virtual-assistant',
    icon: '💼',
  },
  {
    id: 'childcare-education',
    label: 'Childcare & Education',
    serpQuery: 'childcare tutoring education teaching services',
    localSerpQuery: 'childcare tutors education services',
    awinCategory: 'education',
    serviceType: 'both',
    freetrustCategoryId: 'education-tutoring',
    icon: '👶',
  },
  {
    id: 'cleaning',
    label: 'Cleaning Services',
    serpQuery: 'home cleaning office cleaning professional cleaning services',
    serviceType: 'local',
    freetrustCategoryId: 'cleaning',
    icon: '🧹',
  },
  {
    id: 'construction-trades',
    label: 'Construction & Trades',
    serpQuery: 'construction builder plumber electrician trades services',
    serviceType: 'local',
    freetrustCategoryId: 'trades-construction',
    icon: '🏗️',
  },
  {
    id: 'content-writing',
    label: 'Content & Writing',
    serpQuery: 'content writing copywriting blogging SEO writing services',
    serviceType: 'remote',
    freetrustCategoryId: 'writing-content',
    icon: '✍️',
  },
  {
    id: 'creative-arts',
    label: 'Creative & Arts',
    serpQuery: 'creative arts illustration animation graphic art services',
    serviceType: 'remote',
    freetrustCategoryId: 'design-creative',
    icon: '🎨',
  },
  {
    id: 'customer-support',
    label: 'Customer Support',
    serpQuery: 'customer support virtual assistant call centre services',
    serviceType: 'remote',
    freetrustCategoryId: 'virtual-assistant',
    icon: '🎧',
  },
  {
    id: 'delivery-logistics',
    label: 'Delivery & Logistics',
    serpQuery: 'delivery courier logistics moving services',
    serviceType: 'local',
    freetrustCategoryId: 'transport-delivery',
    icon: '🚚',
  },
  {
    id: 'design-branding',
    label: 'Design & Branding',
    serpQuery: 'graphic design branding logo UI UX design services',
    serviceType: 'remote',
    freetrustCategoryId: 'design-creative',
    icon: '🎯',
  },
  {
    id: 'events-entertainment',
    label: 'Events & Entertainment',
    serpQuery: 'event planning entertainment DJ photography videography services',
    localSerpQuery: 'event planners DJs photographers videographers',
    serviceType: 'both',
    freetrustCategoryId: 'events-entertainment',
    icon: '🎉',
  },
  {
    id: 'fitness-personal-training',
    label: 'Fitness & Personal Training',
    serpQuery: 'personal trainer fitness coach gym online fitness services',
    localSerpQuery: 'personal trainers gyms fitness coaches',
    awinCategory: 'health-fitness',
    serviceType: 'both',
    freetrustCategoryId: 'health-wellness',
    icon: '🏋️',
  },
  {
    id: 'gardening-landscaping',
    label: 'Gardening & Landscaping',
    serpQuery: 'gardening landscaping lawn care tree surgery services',
    serviceType: 'local',
    freetrustCategoryId: 'landscaping-gardening',
    icon: '🌱',
  },
  {
    id: 'health-medical',
    label: 'Health & Medical',
    serpQuery: 'health medical therapy counselling telehealth services',
    localSerpQuery: 'therapists counsellors health clinics wellness',
    awinCategory: 'health',
    serviceType: 'both',
    freetrustCategoryId: 'health-wellness',
    icon: '🏥',
  },
  {
    id: 'home-improvement',
    label: 'Home Improvement',
    serpQuery: 'home improvement renovation interior design handyman services',
    serviceType: 'local',
    freetrustCategoryId: 'home-garden',
    icon: '🏠',
  },
  {
    id: 'hr-recruitment',
    label: 'HR & Recruitment',
    serpQuery: 'HR recruitment staffing talent acquisition services',
    localSerpQuery: 'recruitment agencies HR consultants',
    awinCategory: 'recruitment',
    serviceType: 'both',
    freetrustCategoryId: 'business-consulting',
    icon: '👥',
  },
  {
    id: 'insurance',
    label: 'Insurance',
    serpQuery: 'insurance broker home car life health insurance services',
    awinCategory: 'insurance',
    serviceType: 'remote',
    freetrustCategoryId: 'finance-accounting',
    icon: '🛡️',
  },
  {
    id: 'it-tech-support',
    label: 'IT & Tech Support',
    serpQuery: 'IT support computer repair tech helpdesk services',
    localSerpQuery: 'IT support computer repair services',
    serviceType: 'both',
    freetrustCategoryId: 'development-tech',
    icon: '💻',
  },
  {
    id: 'language-translation',
    label: 'Language & Translation',
    serpQuery: 'translation interpreting language tutor services',
    serviceType: 'remote',
    freetrustCategoryId: 'translation-interpretation',
    icon: '🌍',
  },
  {
    id: 'legal-services',
    label: 'Legal Services',
    serpQuery: 'legal solicitor lawyer notary contract services',
    localSerpQuery: 'solicitors legal services notary',
    awinCategory: 'legal',
    serviceType: 'both',
    freetrustCategoryId: 'legal-compliance',
    icon: '⚖️',
  },
  {
    id: 'marketing-seo',
    label: 'Marketing & SEO',
    serpQuery: 'digital marketing SEO social media advertising services',
    serviceType: 'remote',
    freetrustCategoryId: 'marketing-growth',
    icon: '📈',
  },
  {
    id: 'music-audio',
    label: 'Music & Audio',
    serpQuery: 'music production audio recording mixing mastering services',
    localSerpQuery: 'music production audio recording studio',
    serviceType: 'both',
    freetrustCategoryId: 'music-audio',
    icon: '🎵',
  },
  {
    id: 'pet-care',
    label: 'Pet Care',
    serpQuery: 'pet care dog walking grooming veterinary services',
    serviceType: 'local',
    freetrustCategoryId: 'pet-services',
    icon: '🐾',
  },
  {
    id: 'photography-video',
    label: 'Photography & Video',
    serpQuery: 'photography videography photo editing video production services',
    localSerpQuery: 'photographers videographers video production',
    serviceType: 'both',
    freetrustCategoryId: 'photography-editing',
    icon: '📸',
  },
  {
    id: 'property-real-estate',
    label: 'Property & Real Estate',
    serpQuery: 'property real estate letting agent management services',
    localSerpQuery: 'estate agents property management letting agents',
    awinCategory: 'property',
    serviceType: 'both',
    freetrustCategoryId: 'professional-property-services',
    icon: '🏡',
  },
  {
    id: 'security',
    label: 'Security Services',
    serpQuery: 'security guard CCTV alarm installation services',
    serviceType: 'local',
    freetrustCategoryId: 'home-security',
    icon: '🔒',
  },
  {
    id: 'social-media',
    label: 'Social Media Management',
    serpQuery: 'social media management content creation influencer services',
    serviceType: 'remote',
    freetrustCategoryId: 'social-media',
    icon: '📱',
  },
  {
    id: 'software-development',
    label: 'Software Development',
    serpQuery: 'software development web app mobile development services',
    serviceType: 'remote',
    freetrustCategoryId: 'development-tech',
    icon: '⚙️',
  },
  {
    id: 'transport-chauffeur',
    label: 'Transport & Chauffeur',
    serpQuery: 'transport chauffeur taxi private hire driving services',
    serviceType: 'local',
    freetrustCategoryId: 'taxi-drivers',
    icon: '🚗',
  },
  {
    id: 'tutoring-coaching',
    label: 'Tutoring & Coaching',
    serpQuery: 'tutoring life coaching mentoring academic coaching services',
    awinCategory: 'education',
    serviceType: 'both',
    freetrustCategoryId: 'coaching-mentoring',
    icon: '🎓',
  },
  {
    id: 'video-animation',
    label: 'Video & Animation',
    serpQuery: 'video editing animation motion graphics explainer video services',
    serviceType: 'remote',
    freetrustCategoryId: 'video-animation',
    icon: '🎬',
  },
  {
    id: 'virtual-assistant',
    label: 'Virtual Assistant',
    serpQuery: 'virtual assistant admin support data entry remote PA services',
    serviceType: 'remote',
    freetrustCategoryId: 'business-consulting',
    icon: '🤝',
  },
]

export const SERVICES_PER_CATEGORY = 20
export const SERVICES_INITIAL_DISPLAY = 12
export const SERVICES_LOAD_MORE_BATCH = 12
export const SERVICE_ARCHIVE_AFTER_DAYS = 14
