export interface ServiceCategory {
  id: string
  label: string
  serpQuery: string
  localSerpQuery?: string
  awinCategory?: string
  serviceType: 'local' | 'remote' | 'both'
  freetrustCategoryId: string
  icon: string
}

export const SERVICE_CATEGORIES: ServiceCategory[] = [
  {
    id: 'ai-automation',
    label: 'AI & Automation',
    serpQuery: 'AI automation consultants chatbot workflow automation services',
    localSerpQuery: 'AI automation consultants chatbot workflow automation Cork Ireland',
    serviceType: 'both',
    freetrustCategoryId: 'ai-automation',
    icon: '🤖',
  },
  {
    id: 'accounting-finance',
    label: 'Accounting & Finance',
    serpQuery: 'accounting bookkeeping financial services',
    localSerpQuery: 'accountants bookkeepers financial advisors',
    awinCategory: 'financial-services',
    serviceType: 'both',
    freetrustCategoryId: 'finance-accounting',
    icon: '📊',
  },
  {
    id: 'beauty-wellness',
    label: 'Beauty & Wellness',
    serpQuery: 'beauty salon spa wellness therapist services',
    serviceType: 'local',
    freetrustCategoryId: 'beauty-personal-care',
    icon: '💆',
  },
  {
    id: 'builders-construction',
    label: 'Builders & Construction',
    serpQuery: 'builders construction extensions renovations plastering services',
    localSerpQuery: 'builders construction contractors renovations extensions Cork',
    serviceType: 'local',
    freetrustCategoryId: 'builders-construction',
    icon: '🧱',
  },
  {
    id: 'business-consulting',
    label: 'Business Consulting',
    serpQuery: 'business consulting strategy advisory services',
    localSerpQuery: 'business consultants advisors',
    awinCategory: 'business-services',
    serviceType: 'both',
    freetrustCategoryId: 'business-consulting',
    icon: '💼',
  },
  {
    id: 'carpentry-joinery',
    label: 'Carpentry & Joinery',
    serpQuery: 'carpentry joinery kitchen fitting wardrobe decking services',
    localSerpQuery: 'carpenters joiners kitchen fitting decking Cork',
    serviceType: 'local',
    freetrustCategoryId: 'carpentry-joinery',
    icon: '🪚',
  },
  {
    id: 'childcare-education',
    label: 'Childcare & Education',
    serpQuery: 'childcare tutoring education teaching services',
    localSerpQuery: 'childcare tutors education services',
    awinCategory: 'education',
    serviceType: 'both',
    freetrustCategoryId: 'education-tutoring',
    icon: '👶',
  },
  {
    id: 'local-childcare-education',
    label: 'Local Childcare & Education',
    serpQuery: 'childcare babysitting nanny after school care tutoring services',
    localSerpQuery: 'childcare babysitters nannies after school care tutors Cork',
    serviceType: 'local',
    freetrustCategoryId: 'childcare-education',
    icon: '👶',
  },
  {
    id: 'cleaning',
    label: 'Cleaning Services',
    serpQuery: 'home cleaning office cleaning professional cleaning services',
    serviceType: 'local',
    freetrustCategoryId: 'cleaning',
    icon: '🧹',
  },
  {
    id: 'community-services',
    label: 'Community Services',
    serpQuery: 'community support services charities volunteering local projects',
    localSerpQuery: 'community support services charities volunteer organisations Cork',
    serviceType: 'local',
    freetrustCategoryId: 'community-services',
    icon: '🌍',
  },
  {
    id: 'construction-trades',
    label: 'Construction & Trades',
    serpQuery: 'construction builder plumber electrician trades services',
    serviceType: 'local',
    freetrustCategoryId: 'trades-construction',
    icon: '🏗️',
  },
  {
    id: 'content-writing',
    label: 'Content & Writing',
    serpQuery: 'content writing copywriting blogging SEO writing services',
    localSerpQuery: 'copywriters content writers editors Cork Ireland',
    serviceType: 'both',
    freetrustCategoryId: 'writing-content',
    icon: '✍️',
  },
  {
    id: 'creative-arts',
    label: 'Creative & Arts',
    serpQuery: 'creative arts illustration animation graphic art services',
    localSerpQuery: 'graphic designers illustrators creative studios Cork Ireland',
    serviceType: 'both',
    freetrustCategoryId: 'design-creative',
    icon: '🎨',
  },
  {
    id: 'customer-support',
    label: 'Customer Support',
    serpQuery: 'customer support virtual assistant call centre services',
    localSerpQuery: 'customer support services call centres virtual assistant Cork Ireland',
    serviceType: 'both',
    freetrustCategoryId: 'business-consulting',
    icon: '🎧',
  },
  {
    id: 'data-analytics',
    label: 'Data & Analytics',
    serpQuery: 'data analytics business intelligence data visualization dashboard services',
    localSerpQuery: 'data analytics business intelligence consultants Cork Ireland',
    serviceType: 'both',
    freetrustCategoryId: 'data-analytics',
    icon: '📊',
  },
  {
    id: 'delivery-logistics',
    label: 'Delivery & Logistics',
    serpQuery: 'delivery courier logistics moving services',
    serviceType: 'local',
    freetrustCategoryId: 'transport-delivery',
    icon: '🚚',
  },
  {
    id: 'design-branding',
    label: 'Design & Branding',
    serpQuery: 'graphic design branding logo UI UX design services',
    localSerpQuery: 'graphic design branding logo design studios Cork Ireland',
    serviceType: 'both',
    freetrustCategoryId: 'design-creative',
    icon: '🎯',
  },
  {
    id: 'disability-care',
    label: 'Disability Care & Support',
    serpQuery: 'disability care support personal assistant respite mobility services',
    localSerpQuery: 'disability care support respite personal assistant services Cork',
    serviceType: 'local',
    freetrustCategoryId: 'disability-care',
    icon: '♿',
  },
  {
    id: 'driving-instructors',
    label: 'Driving Instructors',
    serpQuery: 'driving instructors EDT lessons pre test automatic lessons',
    localSerpQuery: 'driving instructors EDT driving lessons pre test Cork',
    serviceType: 'local',
    freetrustCategoryId: 'driving-instructors',
    icon: '🚗',
  },
  {
    id: 'elder-care',
    label: 'Elder Care',
    serpQuery: 'elder care home help companionship carer respite services',
    localSerpQuery: 'elder care home help companionship carers respite Cork',
    serviceType: 'local',
    freetrustCategoryId: 'elder-care',
    icon: '🤝',
  },
  {
    id: 'electrical',
    label: 'Electrical',
    serpQuery: 'electrician electrical repairs rewiring lighting installation services',
    localSerpQuery: 'electricians electrical repairs rewiring lighting installation Cork',
    serviceType: 'local',
    freetrustCategoryId: 'electrical',
    icon: '💡',
  },
  {
    id: 'energy-services',
    label: 'Energy Services',
    serpQuery: 'home energy audit insulation boiler servicing BER services',
    localSerpQuery: 'home energy audits insulation BER assessors boiler servicing Cork',
    serviceType: 'local',
    freetrustCategoryId: 'energy-services',
    icon: '⚡',
  },
  {
    id: 'events-entertainment',
    label: 'Events & Entertainment',
    serpQuery: 'event planning entertainment DJ photography videography services',
    localSerpQuery: 'event planners DJs photographers videographers',
    serviceType: 'both',
    freetrustCategoryId: 'events-entertainment',
    icon: '🎉',
  },
  {
    id: 'fitness-personal-training',
    label: 'Fitness & Personal Training',
    serpQuery: 'personal trainer fitness coach gym online fitness services',
    localSerpQuery: 'personal trainers gyms fitness coaches',
    awinCategory: 'health-fitness',
    serviceType: 'both',
    freetrustCategoryId: 'health-wellness',
    icon: '🏋️',
  },
  {
    id: 'flooring-tiling',
    label: 'Flooring & Tiling',
    serpQuery: 'flooring tiling laminate hardwood bathroom tiling services',
    localSerpQuery: 'flooring installers tilers bathroom tiling Cork',
    serviceType: 'local',
    freetrustCategoryId: 'flooring-tiling',
    icon: '◼️',
  },
  {
    id: 'food-catering',
    label: 'Food & Catering',
    serpQuery: 'catering private chef meal prep cake baking services',
    localSerpQuery: 'catering private chef meal prep cakes Cork',
    serviceType: 'local',
    freetrustCategoryId: 'food-catering',
    icon: '🍽️',
  },
  {
    id: 'gardening-landscaping',
    label: 'Gardening & Landscaping',
    serpQuery: 'gardening landscaping lawn care tree surgery services',
    serviceType: 'local',
    freetrustCategoryId: 'landscaping-gardening',
    icon: '🌱',
  },
  {
    id: 'grant-consulting',
    label: 'Grant & Funding Consulting',
    serpQuery: 'grant writing funding consultant SEAI LEADER EU funding services',
    localSerpQuery: 'grant consultants funding advisors SEAI LEADER Cork Ireland',
    serviceType: 'both',
    freetrustCategoryId: 'grant-consulting',
    icon: '💶',
  },
  {
    id: 'handyman',
    label: 'Handyman',
    serpQuery: 'handyman odd jobs furniture assembly home maintenance services',
    localSerpQuery: 'handyman odd jobs furniture assembly home repairs Cork',
    serviceType: 'local',
    freetrustCategoryId: 'handyman',
    icon: '🧰',
  },
  {
    id: 'health-medical',
    label: 'Health & Medical',
    serpQuery: 'health medical therapy counselling telehealth services',
    localSerpQuery: 'therapists counsellors health clinics wellness',
    awinCategory: 'health',
    serviceType: 'both',
    freetrustCategoryId: 'health-wellness',
    icon: '🏥',
  },
  {
    id: 'heating-hvac',
    label: 'Heating & HVAC',
    serpQuery: 'heating HVAC boiler repair heat pump air conditioning services',
    localSerpQuery: 'heating engineers boiler repair HVAC heat pumps Cork',
    serviceType: 'local',
    freetrustCategoryId: 'heating-hvac',
    icon: '♨️',
  },
  {
    id: 'home-improvement',
    label: 'Home Improvement',
    serpQuery: 'home improvement renovation interior design handyman services',
    serviceType: 'local',
    freetrustCategoryId: 'home-garden',
    icon: '🏠',
  },
  {
    id: 'hr-recruitment',
    label: 'HR & Recruitment',
    serpQuery: 'HR recruitment staffing talent acquisition services',
    localSerpQuery: 'recruitment agencies HR consultants',
    awinCategory: 'recruitment',
    serviceType: 'both',
    freetrustCategoryId: 'business-consulting',
    icon: '👥',
  },
  {
    id: 'insurance',
    label: 'Insurance',
    serpQuery: 'insurance broker home car life health insurance services',
    localSerpQuery: 'insurance brokers financial advisors Cork Ireland',
    awinCategory: 'insurance',
    serviceType: 'both',
    freetrustCategoryId: 'finance-accounting',
    icon: '🛡️',
  },
  {
    id: 'it-tech-support',
    label: 'IT & Tech Support',
    serpQuery: 'IT support computer repair tech helpdesk services',
    localSerpQuery: 'IT support computer repair services',
    serviceType: 'both',
    freetrustCategoryId: 'development-tech',
    icon: '💻',
  },
  {
    id: 'language-translation',
    label: 'Language & Translation',
    serpQuery: 'translation interpreting language tutor services',
    localSerpQuery: 'translators interpreters language services Cork Ireland',
    serviceType: 'both',
    freetrustCategoryId: 'translation-interpretation',
    icon: '🌍',
  },
  {
    id: 'legal-services',
    label: 'Legal Services',
    serpQuery: 'legal solicitor lawyer notary contract services',
    localSerpQuery: 'solicitors legal services notary',
    awinCategory: 'legal',
    serviceType: 'both',
    freetrustCategoryId: 'legal-compliance',
    icon: '⚖️',
  },
  {
    id: 'marketing-seo',
    label: 'Marketing & SEO',
    serpQuery: 'digital marketing SEO social media advertising services',
    localSerpQuery: 'digital marketing agencies advertising agencies Cork Ireland',
    serviceType: 'both',
    freetrustCategoryId: 'marketing-growth',
    icon: '📈',
  },
  {
    id: 'moving-services',
    label: 'Moving Services',
    serpQuery: 'house removals man with a van packing moving services',
    localSerpQuery: 'house removals man with a van movers Cork',
    serviceType: 'local',
    freetrustCategoryId: 'moving-services',
    icon: '📦',
  },
  {
    id: 'music-audio',
    label: 'Music & Audio',
    serpQuery: 'music production audio recording mixing mastering services',
    localSerpQuery: 'music production audio recording studio',
    serviceType: 'both',
    freetrustCategoryId: 'music-audio',
    icon: '🎵',
  },
  {
    id: 'music-arts-tuition',
    label: 'Music & Arts Tuition',
    serpQuery: 'music lessons art classes drama tuition guitar piano singing',
    localSerpQuery: 'music lessons art classes drama tuition Cork',
    serviceType: 'local',
    freetrustCategoryId: 'music-arts-tuition',
    icon: '🎵',
  },
  {
    id: 'painting-decorating',
    label: 'Painting & Decorating',
    serpQuery: 'painting decorating wallpapering interior exterior painting services',
    localSerpQuery: 'painters decorators wallpapering Cork',
    serviceType: 'local',
    freetrustCategoryId: 'painting-decorating',
    icon: '🎨',
  },
  {
    id: 'pest-control',
    label: 'Pest Control',
    serpQuery: 'pest control rodent wasp bed bug treatment services',
    localSerpQuery: 'pest control rodent wasp bed bug treatment Cork',
    serviceType: 'local',
    freetrustCategoryId: 'pest-control',
    icon: '🐜',
  },
  {
    id: 'pet-care',
    label: 'Pet Care',
    serpQuery: 'pet care dog walking grooming veterinary services',
    serviceType: 'local',
    freetrustCategoryId: 'pet-services',
    icon: '🐾',
  },
  {
    id: 'plumbing',
    label: 'Plumbing',
    serpQuery: 'plumber emergency plumbing leak repair drain unblocking services',
    localSerpQuery: 'plumbers emergency plumbing leak repair drains Cork',
    serviceType: 'local',
    freetrustCategoryId: 'plumbing',
    icon: '🚰',
  },
  {
    id: 'photography-video',
    label: 'Photography & Video',
    serpQuery: 'photography videography photo editing video production services',
    localSerpQuery: 'photographers videographers video production',
    serviceType: 'both',
    freetrustCategoryId: 'photography-editing',
    icon: '📸',
  },
  {
    id: 'property-real-estate',
    label: 'Property & Real Estate',
    serpQuery: 'property real estate letting agent management services',
    localSerpQuery: 'estate agents property management letting agents',
    awinCategory: 'property',
    serviceType: 'both',
    freetrustCategoryId: 'professional-property-services',
    icon: '🏡',
  },
  {
    id: 'renewable-energy',
    label: 'Renewable Energy',
    serpQuery: 'solar panel installers EV charger heat pump battery storage services',
    localSerpQuery: 'solar panel installers EV charger heat pump battery storage Cork',
    serviceType: 'local',
    freetrustCategoryId: 'renewable-energy',
    icon: '☀️',
  },
  {
    id: 'roofing',
    label: 'Roofing',
    serpQuery: 'roofing roof repair flat roof gutter chimney repair services',
    localSerpQuery: 'roofers roof repairs gutters chimney repairs Cork',
    serviceType: 'local',
    freetrustCategoryId: 'roofing',
    icon: '🏠',
  },
  {
    id: 'field-sales',
    label: 'Field Sales',
    serpQuery: 'field sales promotional staff brand ambassadors retail sales services',
    localSerpQuery: 'field sales promotional staff brand ambassadors Cork',
    serviceType: 'local',
    freetrustCategoryId: 'sales-local',
    icon: '💼',
  },
  {
    id: 'online-sales',
    label: 'Online Sales',
    serpQuery: 'B2B lead generation sales funnel CRM sales outsourcing services',
    localSerpQuery: 'B2B sales consultants lead generation sales training Cork Ireland',
    serviceType: 'both',
    freetrustCategoryId: 'sales-online',
    icon: '💼',
  },
  {
    id: 'security',
    label: 'Security Services',
    serpQuery: 'security guard CCTV alarm installation services',
    serviceType: 'local',
    freetrustCategoryId: 'home-security',
    icon: '🔒',
  },
  {
    id: 'seo-digital',
    label: 'SEO & Digital Marketing',
    serpQuery: 'SEO agency technical SEO local SEO audit digital marketing services',
    localSerpQuery: 'SEO agencies local SEO digital marketing Cork Ireland',
    serviceType: 'both',
    freetrustCategoryId: 'seo-digital',
    icon: '🔍',
  },
  {
    id: 'social-media',
    label: 'Social Media Management',
    serpQuery: 'social media management content creation influencer services',
    localSerpQuery: 'social media management agencies content creators Cork Ireland',
    serviceType: 'both',
    freetrustCategoryId: 'social-media',
    icon: '📱',
  },
  {
    id: 'sports-fitness-coaching',
    label: 'Sports & Fitness Coaching',
    serpQuery: 'sports coaching football swimming martial arts personal training services',
    localSerpQuery: 'sports coaching football swimming martial arts Cork',
    serviceType: 'local',
    freetrustCategoryId: 'sports-fitness-coaching',
    icon: '⚽',
  },
  {
    id: 'software-development',
    label: 'Software Development',
    serpQuery: 'software development web app mobile development services',
    localSerpQuery: 'software developers web developers app developers Cork Ireland',
    serviceType: 'both',
    freetrustCategoryId: 'development-tech',
    icon: '⚙️',
  },
  {
    id: 'vehicle-services',
    label: 'Vehicle Services',
    serpQuery: 'mobile mechanic car valeting tyre fitting NCT preparation services',
    localSerpQuery: 'mobile mechanic car valeting tyre fitting NCT preparation Cork',
    serviceType: 'local',
    freetrustCategoryId: 'vehicle-services',
    icon: '🔧',
  },
  {
    id: 'transport-chauffeur',
    label: 'Transport & Chauffeur',
    serpQuery: 'transport chauffeur taxi private hire driving services',
    serviceType: 'local',
    freetrustCategoryId: 'taxi-drivers',
    icon: '🚗',
  },
  {
    id: 'tutoring-coaching',
    label: 'Tutoring & Coaching',
    serpQuery: 'tutoring life coaching mentoring academic coaching services',
    localSerpQuery: 'tutors life coaches career coaches mentors Cork Ireland',
    awinCategory: 'education',
    serviceType: 'both',
    freetrustCategoryId: 'coaching-mentoring',
    icon: '🎓',
  },
  {
    id: 'video-animation',
    label: 'Video & Animation',
    serpQuery: 'video editing animation motion graphics explainer video services',
    localSerpQuery: 'video production animation studios videographers Cork Ireland',
    serviceType: 'both',
    freetrustCategoryId: 'video-animation',
    icon: '🎬',
  },
  {
    id: 'virtual-assistant',
    label: 'Virtual Assistant',
    serpQuery: 'virtual assistant admin support data entry remote PA services',
    localSerpQuery: 'administration support personal assistant services Cork Ireland',
    serviceType: 'both',
    freetrustCategoryId: 'business-consulting',
    icon: '🤝',
  },
]

export const SERVICES_PER_CATEGORY = 24
export const SERVICES_INITIAL_DISPLAY = 12
export const SERVICES_LOAD_MORE_BATCH = 12
export const SERVICE_ARCHIVE_AFTER_DAYS = 14
