import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  'https://tioqakxnqjxyuzgnwhrb.supabase.co',
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpb3Fha3hucWp4eXV6Z253aHJiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NTUwNzc5OCwiZXhwIjoyMDkxMDgzNzk4fQ.gn5-rMINbSUKJEiNa733DIG8QK68jb7lUg0OPIz8efg',
  { auth: { persistSession: false } }
)

async function main() {
  // Get a real creator_id
  const { data: profiles, error: profileErr } = await supabase.from('profiles').select('id').limit(1)
  if (profileErr) { console.error('Profile fetch error:', profileErr); process.exit(1) }
  const creatorId = profiles?.[0]?.id
  if (!creatorId) throw new Error('No profiles found — cannot seed events without a valid creator_id')
  console.log('Using creator_id:', creatorId)

  const base = new Date('2026-04-19T00:00:00Z')
  const d = (daysFromNow: number, hour = 10): string => {
    const dt = new Date(base)
    dt.setDate(dt.getDate() + daysFromNow)
    dt.setHours(hour, 0, 0, 0)
    return dt.toISOString()
  }

  const events = [
    // === IRISH IN-PERSON EVENTS ===
    {
      creator_id: creatorId, title: 'Dublin Tech Summit 2026', description: "Ireland's largest technology conference bringing together 2000+ developers, founders, and investors. Featuring keynotes on AI, Web3, and the future of work. Networking sessions, startup pitches, and workshops throughout the day.", category: 'Technology', tags: ['tech', 'ai', 'networking', 'startups'], status: 'published', starts_at: d(3, 9), ends_at: d(3, 18), timezone: 'Europe/Dublin', is_online: false, venue_name: 'Convention Centre Dublin', venue_address: 'Spencer Dock, North Wall Quay, Dublin 1', is_paid: true, ticket_price: 149, ticket_price_eur: 149, currency_code: 'EUR', attendee_count: 1840, country: 'IE', city: 'Dublin', latitude: 53.3498, longitude: -6.2603, location_label: 'Dublin, Ireland', organiser_name: 'TechIreland'
    },
    {
      creator_id: creatorId, title: 'Cork Startup Weekend', description: 'A 54-hour event where developers, designers, marketers, and business professionals come together to build and launch startups. Mentors from top Irish companies and VCs will be on hand.', category: 'Business', tags: ['startup', 'entrepreneurship', 'hackathon', 'cork'], status: 'published', starts_at: d(5, 18), ends_at: d(7, 20), timezone: 'Europe/Dublin', is_online: false, venue_name: 'Cork Innovation Hub', venue_address: 'Grand Parade, Cork', is_paid: true, ticket_price: 50, ticket_price_eur: 50, currency_code: 'EUR', attendee_count: 120, country: 'IE', city: 'Cork', latitude: 51.8985, longitude: -8.4756, location_label: 'Cork, Ireland', organiser_name: 'Startup Cork'
    },
    {
      creator_id: creatorId, title: 'Galway Arts & Culture Festival', description: "A celebration of Galway's rich arts scene featuring local painters, sculptors, musicians, and performance artists. Free entry, family-friendly, with workshops for all ages.", category: 'Community', tags: ['arts', 'culture', 'galway', 'free'], status: 'published', starts_at: d(8, 11), ends_at: d(8, 20), timezone: 'Europe/Dublin', is_online: false, venue_name: 'Eyre Square', venue_address: 'Eyre Square, Galway', is_paid: false, ticket_price: 0, ticket_price_eur: 0, currency_code: 'EUR', attendee_count: 450, country: 'IE', city: 'Galway', latitude: 53.2707, longitude: -9.0568, location_label: 'Galway, Ireland', organiser_name: 'Galway City Council'
    },
    {
      creator_id: creatorId, title: 'Limerick Health & Wellness Expo', description: 'A full-day wellness expo featuring yoga sessions, nutrition talks, mental health workshops, and holistic therapy demonstrations. Meet local wellness practitioners and discover new approaches to healthy living.', category: 'Health', tags: ['wellness', 'yoga', 'nutrition', 'mindfulness'], status: 'published', starts_at: d(10, 9), ends_at: d(10, 17), timezone: 'Europe/Dublin', is_online: false, venue_name: 'Limerick Racecourse', venue_address: 'Patrickswell, Limerick', is_paid: true, ticket_price: 25, ticket_price_eur: 25, currency_code: 'EUR', attendee_count: 380, country: 'IE', city: 'Limerick', latitude: 52.6638, longitude: -8.6267, location_label: 'Limerick, Ireland', organiser_name: 'Limerick Wellness Hub'
    },
    {
      creator_id: creatorId, title: 'Belfast FinTech Forum', description: 'Northern Ireland\'s premier fintech event, bringing together banks, payment providers, regulators, and startups. Panel discussions on open banking, crypto regulation, and embedded finance.', category: 'Finance', tags: ['fintech', 'banking', 'crypto', 'belfast'], status: 'published', starts_at: d(12, 9), ends_at: d(12, 17), timezone: 'Europe/London', is_online: false, venue_name: 'ICC Belfast', venue_address: '2 Lanyon Pl, Belfast BT1 3WH', is_paid: true, ticket_price: 95, ticket_price_eur: 112, currency_code: 'GBP', attendee_count: 560, country: 'GB', city: 'Belfast', latitude: 54.5973, longitude: -5.9301, location_label: 'Belfast, Northern Ireland', organiser_name: 'FinTech NI'
    },
    {
      creator_id: creatorId, title: 'Dublin Climate Action Summit', description: "Ireland's leading sustainability event, uniting environmentalists, policymakers, entrepreneurs, and citizens to tackle climate change. Sessions on renewable energy, circular economy, and green building.", category: 'Sustainability', tags: ['climate', 'sustainability', 'green', 'environment'], status: 'published', starts_at: d(15, 9), ends_at: d(15, 18), timezone: 'Europe/Dublin', is_online: false, venue_name: 'RDS Arena', venue_address: 'Anglesea Rd, Ballsbridge, Dublin 4', is_paid: false, ticket_price: 0, ticket_price_eur: 0, currency_code: 'EUR', attendee_count: 1200, country: 'IE', city: 'Dublin', latitude: 53.3202, longitude: -6.2279, location_label: 'Dublin 4, Ireland', organiser_name: 'Climate Action Ireland'
    },
    {
      creator_id: creatorId, title: 'Waterford Design Week', description: 'A week-long celebration of graphic design, UX, product design, and architecture. Portfolio reviews, studio tours, talks from design leaders, and a graduate showcase.', category: 'Design', tags: ['design', 'ux', 'graphic-design', 'architecture'], status: 'published', starts_at: d(14, 10), ends_at: d(21, 18), timezone: 'Europe/Dublin', is_online: false, venue_name: 'Waterford Treasures', venue_address: 'The Viking Triangle, Waterford', is_paid: false, ticket_price: 0, ticket_price_eur: 0, currency_code: 'EUR', attendee_count: 340, country: 'IE', city: 'Waterford', latitude: 52.2593, longitude: -7.1101, location_label: 'Waterford, Ireland', organiser_name: 'Design Waterford'
    },
    {
      creator_id: creatorId, title: 'Irish Founders Breakfast Club', description: 'Monthly breakfast meetup for Irish founders and early-stage startup founders. Informal networking, 3-minute pitches, and a guest speaker. Limited to 40 attendees for quality conversations.', category: 'Business', tags: ['founders', 'networking', 'startup', 'early-stage'], status: 'published', starts_at: d(6, 8), ends_at: d(6, 10), timezone: 'Europe/Dublin', is_online: false, venue_name: 'The Marker Hotel', venue_address: 'Grand Canal Square, Dublin 2', is_paid: true, ticket_price: 15, ticket_price_eur: 15, currency_code: 'EUR', attendee_count: 38, country: 'IE', city: 'Dublin', latitude: 53.3384, longitude: -6.2396, location_label: 'Dublin 2, Ireland', organiser_name: 'Founders Ireland'
    },
    {
      creator_id: creatorId, title: 'Kilkenny Medieval Festival', description: "Step back in time at Kilkenny's spectacular medieval festival. Jousting tournaments, craft markets, period costumes, storytelling, and traditional Irish food and music.", category: 'Community', tags: ['history', 'medieval', 'festival', 'family'], status: 'published', starts_at: d(20, 10), ends_at: d(22, 18), timezone: 'Europe/Dublin', is_online: false, venue_name: 'Kilkenny Castle', venue_address: 'The Parade, Kilkenny', is_paid: true, ticket_price: 12, ticket_price_eur: 12, currency_code: 'EUR', attendee_count: 890, country: 'IE', city: 'Kilkenny', latitude: 52.6541, longitude: -7.2448, location_label: 'Kilkenny, Ireland', organiser_name: 'Kilkenny Tourism'
    },
    {
      creator_id: creatorId, title: 'Dublin AI & Machine Learning Meetup', description: 'Monthly gathering of ML engineers, data scientists, and AI researchers. This month: LLM fine-tuning techniques, RAG architectures, and a demo showcase from local AI startups.', category: 'Technology', tags: ['ai', 'machine-learning', 'llm', 'data-science'], status: 'published', starts_at: d(9, 18), ends_at: d(9, 21), timezone: 'Europe/Dublin', is_online: false, venue_name: 'Google Ireland HQ', venue_address: 'Gordon House, 4 Barrow St, Dublin 4', is_paid: false, ticket_price: 0, ticket_price_eur: 0, currency_code: 'EUR', attendee_count: 180, country: 'IE', city: 'Dublin', latitude: 53.3388, longitude: -6.2380, location_label: 'Dublin 4, Ireland', organiser_name: 'Dublin AI Community'
    },
    {
      creator_id: creatorId, title: 'Cork Food & Drink Festival', description: "Celebrate the best of Cork's world-renowned food scene. Local producers, artisan food stalls, cooking demonstrations by Michelin-starred chefs, and wine and whiskey tastings.", category: 'Community', tags: ['food', 'drink', 'gastronomy', 'cork', 'local'], status: 'published', starts_at: d(18, 11), ends_at: d(18, 19), timezone: 'Europe/Dublin', is_online: false, venue_name: 'English Market', venue_address: 'Grand Parade, Cork', is_paid: false, ticket_price: 0, ticket_price_eur: 0, currency_code: 'EUR', attendee_count: 720, country: 'IE', city: 'Cork', latitude: 51.8985, longitude: -8.4756, location_label: 'Cork, Ireland', organiser_name: 'Cork Food Network'
    },
    {
      creator_id: creatorId, title: 'Sligo Surf & Adventure Sports Weekend', description: "Ireland's surf capital comes alive with surf lessons, paddleboarding, coasteering, and kayaking. Suitable for all levels from beginners to experienced adventurers.", category: 'Health', tags: ['surfing', 'adventure', 'outdoor', 'sport'], status: 'published', starts_at: d(25, 9), ends_at: d(26, 18), timezone: 'Europe/Dublin', is_online: false, venue_name: 'Strandhill Beach', venue_address: 'Strandhill, Co. Sligo', is_paid: true, ticket_price: 75, ticket_price_eur: 75, currency_code: 'EUR', attendee_count: 210, country: 'IE', city: 'Sligo', latitude: 54.2697, longitude: -8.4842, location_label: 'Sligo, Ireland', organiser_name: 'Surf Sligo'
    },
    {
      creator_id: creatorId, title: 'Drogheda Blockchain & Web3 Conference', description: 'Exploring the future of decentralised finance, NFTs, and blockchain infrastructure. Hear from project founders, regulators, and institutional investors about the road ahead for Web3.', category: 'Technology', tags: ['blockchain', 'web3', 'defi', 'crypto'], status: 'published', starts_at: d(30, 10), ends_at: d(30, 17), timezone: 'Europe/Dublin', is_online: false, venue_name: 'Drogheda Arts Centre', venue_address: 'Stockwell Lane, Drogheda, Co. Louth', is_paid: true, ticket_price: 60, ticket_price_eur: 60, currency_code: 'EUR', attendee_count: 230, country: 'IE', city: 'Drogheda', latitude: 53.7179, longitude: -6.3561, location_label: 'Drogheda, Ireland', organiser_name: 'Web3 Ireland'
    },
    {
      creator_id: creatorId, title: 'Wicklow Mountain Trail Run', description: 'A scenic 10km trail run through the Wicklow Mountains, suitable for intermediate runners. Stunning views of Glendalough and Luggala. Post-run breakfast included.', category: 'Health', tags: ['trail-running', 'wicklow', 'outdoor', 'fitness'], status: 'published', starts_at: d(2, 8), ends_at: d(2, 12), timezone: 'Europe/Dublin', is_online: false, venue_name: 'Glendalough Visitor Centre', venue_address: 'Glendalough, Co. Wicklow', is_paid: true, ticket_price: 20, ticket_price_eur: 20, currency_code: 'EUR', attendee_count: 95, country: 'IE', city: 'Wicklow', latitude: 52.9906, longitude: -6.3318, location_label: 'Glendalough, Co. Wicklow', organiser_name: 'Wild Wicklow Runs'
    },
    {
      creator_id: creatorId, title: 'Dun Laoghaire Maritime Festival', description: "Annual maritime festival celebrating Dublin's seafaring history. Boat trips, sea swimming, food stalls, live music, and a spectacular fireworks finale over the harbour.", category: 'Community', tags: ['maritime', 'festival', 'coastal', 'family', 'dublin'], status: 'published', starts_at: d(44, 11), ends_at: d(44, 21), timezone: 'Europe/Dublin', is_online: false, venue_name: 'Dun Laoghaire Harbour', venue_address: 'Dun Laoghaire, Co. Dublin', is_paid: false, ticket_price: 0, ticket_price_eur: 0, currency_code: 'EUR', attendee_count: 3200, country: 'IE', city: 'Dublin', latitude: 53.2940, longitude: -6.1358, location_label: 'Dun Laoghaire, Dublin', organiser_name: 'Maritime Dublin'
    },
    {
      creator_id: creatorId, title: 'Maynooth University Research Open Day', description: 'Explore cutting-edge research across departments: computer science, humanities, social science, and science. Lab tours, researcher talks, and PhD programme information.', category: 'Education', tags: ['university', 'research', 'education', 'phd', 'maynooth'], status: 'published', starts_at: d(47, 10), ends_at: d(47, 16), timezone: 'Europe/Dublin', is_online: false, venue_name: 'Maynooth University', venue_address: 'North Campus, Maynooth, Co. Kildare', is_paid: false, ticket_price: 0, ticket_price_eur: 0, currency_code: 'EUR', attendee_count: 450, country: 'IE', city: 'Maynooth', latitude: 53.3816, longitude: -6.5922, location_label: 'Maynooth, Co. Kildare', organiser_name: 'Maynooth University'
    },
    {
      creator_id: creatorId, title: 'Athlone Agri-Tech Innovation Day', description: 'A showcase of Irish agricultural technology — precision farming, drone monitoring, soil sensors, and sustainable livestock management. Farmer networking session and farm visits.', category: 'Technology', tags: ['agritech', 'farming', 'precision-agriculture', 'ireland'], status: 'published', starts_at: d(49, 9), ends_at: d(49, 17), timezone: 'Europe/Dublin', is_online: false, venue_name: 'Athlone Springs Hotel', venue_address: 'Athlone, Co. Westmeath', is_paid: true, ticket_price: 30, ticket_price_eur: 30, currency_code: 'EUR', attendee_count: 190, country: 'IE', city: 'Athlone', latitude: 53.4239, longitude: -7.9407, location_label: 'Athlone, Co. Westmeath', organiser_name: 'AgriTech Ireland'
    },
    {
      creator_id: creatorId, title: 'Wexford Literary Festival', description: "A weekend celebration of Irish and international literature. Author readings, book launches, panel discussions, and children's storytelling sessions in the beautiful town of Wexford.", category: 'Education', tags: ['literature', 'books', 'reading', 'wexford', 'culture'], status: 'published', starts_at: d(53, 11), ends_at: d(54, 18), timezone: 'Europe/Dublin', is_online: false, venue_name: 'Wexford Arts Centre', venue_address: 'Cornmarket, Wexford', is_paid: true, ticket_price: 10, ticket_price_eur: 10, currency_code: 'EUR', attendee_count: 280, country: 'IE', city: 'Wexford', latitude: 52.3369, longitude: -6.4633, location_label: 'Wexford, Ireland', organiser_name: 'Wexford Literary Society'
    },
    {
      creator_id: creatorId, title: 'Dublin Charity Gala Dinner', description: 'Black tie fundraising dinner in aid of three Irish charities: Pieta House, DSPCA, and Focus Ireland. A wonderful evening with live entertainment, a charity auction, and a 4-course meal.', category: 'Community', tags: ['charity', 'fundraising', 'gala', 'dublin', 'blacktie'], status: 'published', starts_at: d(57, 19), ends_at: d(57, 23), timezone: 'Europe/Dublin', is_online: false, venue_name: 'Clayton Hotel Burlington Road', venue_address: 'Upper Leeson St, Dublin 4', is_paid: true, ticket_price: 150, ticket_price_eur: 150, currency_code: 'EUR', attendee_count: 320, country: 'IE', city: 'Dublin', latitude: 53.3294, longitude: -6.2402, location_label: 'Dublin 4, Ireland', organiser_name: 'Charity Ireland Network'
    },

    // === ONLINE EVENTS ===
    {
      creator_id: creatorId, title: 'FreeTrust Community Townhall Q2 2026', description: 'Join the FreeTrust team and community for our quarterly townhall. Product updates, community metrics, upcoming feature previews, and open Q&A. All members welcome.', category: 'Community', tags: ['freetrust', 'community', 'townhall', 'online'], status: 'published', starts_at: d(4, 17), ends_at: d(4, 18), timezone: 'UTC', is_online: true, meeting_url: 'https://freetrust.co/community', is_paid: false, ticket_price: 0, ticket_price_eur: 0, currency_code: 'EUR', attendee_count: 890, country: null, city: null, latitude: null, longitude: null, location_label: 'Online', organiser_name: 'FreeTrust Team'
    },
    {
      creator_id: creatorId, title: 'Zero to SaaS: Building Profitable Products in 2026', description: 'A live 2-hour workshop on building and launching SaaS products from zero with minimal code. Covers ideation, validation, no-code tools, pricing, and growth hacking. Recording available to all registrants.', category: 'Business', tags: ['saas', 'startups', 'online', 'workshop', 'indie-hackers'], status: 'published', starts_at: d(7, 19), ends_at: d(7, 21), timezone: 'UTC', is_online: true, meeting_url: 'https://zoom.us/webinar', is_paid: true, ticket_price: 29, ticket_price_eur: 29, currency_code: 'EUR', attendee_count: 340, country: null, city: null, latitude: null, longitude: null, location_label: 'Online', organiser_name: 'Maker Summit'
    },
    {
      creator_id: creatorId, title: 'European AI Policy Roundtable', description: 'An online policy discussion on the EU AI Act, copyright, data governance, and cross-border AI deployment. Featuring MEPs, legal experts, and tech policy advisors.', category: 'Technology', tags: ['ai', 'policy', 'eu', 'regulation'], status: 'published', starts_at: d(11, 14), ends_at: d(11, 16), timezone: 'Europe/Berlin', is_online: true, meeting_url: 'https://zoom.us/webinar', is_paid: false, ticket_price: 0, ticket_price_eur: 0, currency_code: 'EUR', attendee_count: 670, country: null, city: null, latitude: null, longitude: null, location_label: 'Online', organiser_name: 'EuroAI Forum'
    },
    {
      creator_id: creatorId, title: 'Freelancer Finance Masterclass', description: 'Everything freelancers need to know about managing money: invoicing, tax, VAT, pension planning, and setting rates. Practical advice from accountants who specialise in self-employed professionals.', category: 'Finance', tags: ['freelance', 'tax', 'finance', 'self-employed'], status: 'published', starts_at: d(13, 12), ends_at: d(13, 14), timezone: 'Europe/Dublin', is_online: true, meeting_url: 'https://zoom.us/webinar', is_paid: true, ticket_price: 19, ticket_price_eur: 19, currency_code: 'EUR', attendee_count: 210, country: null, city: null, latitude: null, longitude: null, location_label: 'Online', organiser_name: 'FreelanceIQ'
    },
    {
      creator_id: creatorId, title: 'UX Research Methods Workshop', description: 'A hands-on online workshop covering user interviews, usability testing, card sorting, and affinity mapping. Includes live practice exercises and template downloads.', category: 'Design', tags: ['ux', 'research', 'design', 'workshop'], status: 'published', starts_at: d(16, 18), ends_at: d(16, 21), timezone: 'Europe/London', is_online: true, meeting_url: 'https://zoom.us/webinar', is_paid: true, ticket_price: 45, ticket_price_eur: 45, currency_code: 'EUR', attendee_count: 145, country: null, city: null, latitude: null, longitude: null, location_label: 'Online', organiser_name: 'Design Skills Academy'
    },
    {
      creator_id: creatorId, title: 'Climate Tech Investor Pitch Night', description: 'Eight climate tech startups pitch to a panel of impact investors and VCs. Public audience welcome to watch live. Q&A with founders after each pitch.', category: 'Sustainability', tags: ['climate-tech', 'investment', 'startup', 'green'], status: 'published', starts_at: d(19, 18), ends_at: d(19, 20), timezone: 'UTC', is_online: true, meeting_url: 'https://zoom.us/webinar', is_paid: false, ticket_price: 0, ticket_price_eur: 0, currency_code: 'EUR', attendee_count: 520, country: null, city: null, latitude: null, longitude: null, location_label: 'Online', organiser_name: 'Green Ventures'
    },
    {
      creator_id: creatorId, title: 'Mindfulness & Meditation for Professionals', description: 'A guided 60-minute online session combining mindfulness practice, breathwork, and stress-reduction techniques. Ideal for busy professionals. No experience needed.', category: 'Health', tags: ['mindfulness', 'meditation', 'wellness', 'stress'], status: 'published', starts_at: d(22, 7), ends_at: d(22, 8), timezone: 'Europe/Dublin', is_online: true, meeting_url: 'https://zoom.us/meeting', is_paid: false, ticket_price: 0, ticket_price_eur: 0, currency_code: 'EUR', attendee_count: 280, country: null, city: null, latitude: null, longitude: null, location_label: 'Online', organiser_name: 'Mindful at Work'
    },
    {
      creator_id: creatorId, title: 'Product Management AMA: Senior PMs from Google, Stripe & Shopify', description: 'An open Q&A session with senior product managers from three of the world\'s top product companies. Submit your questions in advance or ask live. One hour, no slides, all insight.', category: 'Business', tags: ['product-management', 'career', 'ama', 'google', 'stripe'], status: 'published', starts_at: d(23, 17), ends_at: d(23, 18), timezone: 'UTC', is_online: true, meeting_url: 'https://zoom.us/webinar', is_paid: false, ticket_price: 0, ticket_price_eur: 0, currency_code: 'EUR', attendee_count: 1100, country: null, city: null, latitude: null, longitude: null, location_label: 'Online', organiser_name: 'PM Community'
    },
    {
      creator_id: creatorId, title: 'Remote Work & Digital Nomad Roundtable', description: 'Monthly discussion for remote workers and digital nomads. Topics: visa regulations, tax residency, coworking across time zones, and building distributed teams. Open mic format.', category: 'Community', tags: ['remote-work', 'digital-nomad', 'async', 'travel'], status: 'published', starts_at: d(27, 19), ends_at: d(27, 21), timezone: 'UTC', is_online: true, meeting_url: 'https://meet.google.com', is_paid: false, ticket_price: 0, ticket_price_eur: 0, currency_code: 'EUR', attendee_count: 340, country: null, city: null, latitude: null, longitude: null, location_label: 'Online', organiser_name: 'Nomad Network'
    },
    {
      creator_id: creatorId, title: 'Advanced React Patterns Workshop', description: 'Deep dive into advanced React patterns: compound components, render props, custom hooks, context optimisation, and concurrent features. Intermediate to advanced level. Code-along format.', category: 'Technology', tags: ['react', 'javascript', 'frontend', 'workshop'], status: 'published', starts_at: d(29, 18), ends_at: d(29, 21), timezone: 'UTC', is_online: true, meeting_url: 'https://zoom.us/webinar', is_paid: true, ticket_price: 39, ticket_price_eur: 39, currency_code: 'EUR', attendee_count: 280, country: null, city: null, latitude: null, longitude: null, location_label: 'Online', organiser_name: 'Frontend Masters Live'
    },
    {
      creator_id: creatorId, title: 'Women in Tech Leadership Summit (Virtual)', description: 'Celebrating and accelerating women in technology leadership. Panel discussions, workshops on negotiation and executive presence, and a mentorship speed-dating session.', category: 'Technology', tags: ['women-in-tech', 'leadership', 'diversity', 'inclusion'], status: 'published', starts_at: d(31, 10), ends_at: d(31, 16), timezone: 'UTC', is_online: true, meeting_url: 'https://zoom.us/webinar', is_paid: false, ticket_price: 0, ticket_price_eur: 0, currency_code: 'EUR', attendee_count: 1450, country: null, city: null, latitude: null, longitude: null, location_label: 'Online', organiser_name: 'Women in Tech Global'
    },
    {
      creator_id: creatorId, title: 'Impact Investing 101 Webinar', description: 'An introduction to impact investing for individuals and family offices. What is impact, how to measure it, which asset classes to consider, and how to build a values-aligned portfolio.', category: 'Finance', tags: ['impact-investing', 'esg', 'sustainable-finance', 'webinar'], status: 'published', starts_at: d(33, 13), ends_at: d(33, 15), timezone: 'Europe/London', is_online: true, meeting_url: 'https://zoom.us/webinar', is_paid: false, ticket_price: 0, ticket_price_eur: 0, currency_code: 'EUR', attendee_count: 410, country: null, city: null, latitude: null, longitude: null, location_label: 'Online', organiser_name: 'Impact Capital'
    },
    {
      creator_id: creatorId, title: 'Figma to Code: Design-Dev Handoff Workshop', description: 'A practical workshop bridging the gap between designers and developers. Figma component architecture, design tokens, auto-layout, and tools like Zeplin, Supernova, and Locofy.', category: 'Design', tags: ['figma', 'design-systems', 'workshop', 'frontend'], status: 'published', starts_at: d(36, 17), ends_at: d(36, 19), timezone: 'Europe/London', is_online: true, meeting_url: 'https://zoom.us/webinar', is_paid: true, ticket_price: 35, ticket_price_eur: 35, currency_code: 'EUR', attendee_count: 190, country: null, city: null, latitude: null, longitude: null, location_label: 'Online', organiser_name: 'DesignCode Academy'
    },
    {
      creator_id: creatorId, title: 'Solar & Battery Storage: Home Energy Revolution', description: 'Everything homeowners need to know about installing solar panels and home battery systems. ROI calculations, grant schemes, grid export, and virtual power plant programmes.', category: 'Sustainability', tags: ['solar', 'battery', 'home-energy', 'renewables'], status: 'published', starts_at: d(37, 19), ends_at: d(37, 20), timezone: 'Europe/Dublin', is_online: true, meeting_url: 'https://zoom.us/webinar', is_paid: false, ticket_price: 0, ticket_price_eur: 0, currency_code: 'EUR', attendee_count: 620, country: null, city: null, latitude: null, longitude: null, location_label: 'Online', organiser_name: 'Solar Ireland'
    },
    {
      creator_id: creatorId, title: 'Mental Health First Aid for Managers', description: 'A certified 4-hour online course training managers to recognise and respond to mental health challenges in their teams. Covers anxiety, depression, burnout, and crisis intervention.', category: 'Health', tags: ['mental-health', 'management', 'wellbeing', 'hr'], status: 'published', starts_at: d(41, 9), ends_at: d(41, 13), timezone: 'Europe/London', is_online: true, meeting_url: 'https://zoom.us/meeting', is_paid: true, ticket_price: 55, ticket_price_eur: 55, currency_code: 'EUR', attendee_count: 85, country: null, city: null, latitude: null, longitude: null, location_label: 'Online', organiser_name: 'Workplace Wellness Institute'
    },
    {
      creator_id: creatorId, title: 'Irish Language Revival Workshop: Beginners', description: 'An engaging beginner\'s course in Irish (Gaeilge) for those who want to reconnect with the language. Conversational focus, no grammar overload — just real phrases for everyday life.', category: 'Education', tags: ['irish', 'gaeilge', 'language', 'culture', 'online'], status: 'published', starts_at: d(43, 19), ends_at: d(43, 20), timezone: 'Europe/Dublin', is_online: true, meeting_url: 'https://zoom.us/meeting', is_paid: true, ticket_price: 20, ticket_price_eur: 20, currency_code: 'EUR', attendee_count: 62, country: null, city: null, latitude: null, longitude: null, location_label: 'Online', organiser_name: 'Gaeilge Beo'
    },
    {
      creator_id: creatorId, title: 'Startup Fundraising Bootcamp: Seed to Series A', description: 'Three-hour intensive on raising venture capital. Deck structure, investor targeting, term sheet negotiation, and how to run a competitive process. With live pitch feedback.', category: 'Business', tags: ['fundraising', 'vc', 'pitch', 'startup', 'seed'], status: 'published', starts_at: d(46, 17), ends_at: d(46, 20), timezone: 'UTC', is_online: true, meeting_url: 'https://zoom.us/webinar', is_paid: true, ticket_price: 79, ticket_price_eur: 79, currency_code: 'EUR', attendee_count: 365, country: null, city: null, latitude: null, longitude: null, location_label: 'Online', organiser_name: 'VC Ready'
    },

    // === GLOBAL IN-PERSON EVENTS ===
    {
      creator_id: creatorId, title: 'London Web3 Summit', description: "The UK's premier Web3 conference, bringing together 3000+ builders, investors, and regulators. Keynotes, workshops, hackathon, and an epic afterparty. Canary Wharf, London.", category: 'Technology', tags: ['web3', 'blockchain', 'london', 'crypto'], status: 'published', starts_at: d(17, 9), ends_at: d(17, 18), timezone: 'Europe/London', is_online: false, venue_name: 'ExCeL London', venue_address: 'Royal Victoria Dock, London E16 1XL', is_paid: true, ticket_price: 299, ticket_price_eur: 350, currency_code: 'GBP', attendee_count: 2800, country: 'GB', city: 'London', latitude: 51.5074, longitude: -0.1278, location_label: 'London, UK', organiser_name: 'Web3 Events UK'
    },
    {
      creator_id: creatorId, title: 'Amsterdam Sustainability Congress', description: 'Three days of deep-dive sessions, site visits to Dutch circular economy leaders, and workshops on sustainable urban planning, renewable energy, and regenerative agriculture.', category: 'Sustainability', tags: ['sustainability', 'circular-economy', 'netherlands', 'climate'], status: 'published', starts_at: d(24, 9), ends_at: d(26, 17), timezone: 'Europe/Amsterdam', is_online: false, venue_name: 'RAI Amsterdam', venue_address: 'Europaplein 24, 1078 GZ Amsterdam', is_paid: true, ticket_price: 350, ticket_price_eur: 350, currency_code: 'EUR', attendee_count: 1650, country: 'NL', city: 'Amsterdam', latitude: 52.3676, longitude: 4.9041, location_label: 'Amsterdam, Netherlands', organiser_name: 'Green World Congress'
    },
    {
      creator_id: creatorId, title: 'Berlin Design Week: Interactive Design & Motion', description: 'Part of Berlin Design Week — a full-day summit focused on interactive design, motion graphics, and digital experiences. Portfolio reviews, live demos, and afterparty at Studio Berlin.', category: 'Design', tags: ['design', 'motion', 'interactive', 'berlin'], status: 'published', starts_at: d(28, 10), ends_at: d(28, 22), timezone: 'Europe/Berlin', is_online: false, venue_name: 'STATION Berlin', venue_address: 'Luckenwalder Str. 4-6, 10963 Berlin', is_paid: true, ticket_price: 89, ticket_price_eur: 89, currency_code: 'EUR', attendee_count: 760, country: 'DE', city: 'Berlin', latitude: 52.5200, longitude: 13.4050, location_label: 'Berlin, Germany', organiser_name: 'Berlin Design Society'
    },
    {
      creator_id: creatorId, title: 'Paris HealthTech Innovation Forum', description: 'Bringing together medtech startups, hospital systems, insurers, and regulators to discuss the future of digital health. Precision medicine, AI diagnostics, remote monitoring, and patient data privacy.', category: 'Health', tags: ['healthtech', 'medtech', 'ai', 'paris'], status: 'published', starts_at: d(32, 9), ends_at: d(32, 18), timezone: 'Europe/Paris', is_online: false, venue_name: 'Palais des Congres', venue_address: '2 Pl. de la Pte Maillot, 75017 Paris', is_paid: true, ticket_price: 180, ticket_price_eur: 180, currency_code: 'EUR', attendee_count: 940, country: 'FR', city: 'Paris', latitude: 48.8566, longitude: 2.3522, location_label: 'Paris, France', organiser_name: 'HealthTech France'
    },
    {
      creator_id: creatorId, title: 'Barcelona Growth Summit', description: "A two-day summit for growth marketers, product leaders, and founders. Topics include viral loops, retention mechanics, B2B go-to-market, and community-led growth. Barcelona's most vibrant startup event.", category: 'Business', tags: ['growth', 'marketing', 'product', 'barcelona', 'startup'], status: 'published', starts_at: d(35, 9), ends_at: d(36, 18), timezone: 'Europe/Madrid', is_online: false, venue_name: 'Fira Gran Via', venue_address: 'Av. Joan Carles I, 64, 08908 Barcelona', is_paid: true, ticket_price: 250, ticket_price_eur: 250, currency_code: 'EUR', attendee_count: 2100, country: 'ES', city: 'Barcelona', latitude: 41.3851, longitude: 2.1734, location_label: 'Barcelona, Spain', organiser_name: 'Growth Summit EU'
    },
    {
      creator_id: creatorId, title: 'New York Social Impact Conference', description: 'Annual gathering of NGO leaders, impact investors, CSR professionals, and social entrepreneurs. Panel on measuring impact, keynotes from leading philanthropists, and a startup showcase focused on SDG-aligned businesses.', category: 'Community', tags: ['social-impact', 'ngo', 'sdg', 'new-york'], status: 'published', starts_at: d(40, 8), ends_at: d(40, 18), timezone: 'America/New_York', is_online: false, venue_name: 'Javits Center', venue_address: '429 11th Ave, New York, NY 10001', is_paid: true, ticket_price: 195, ticket_price_eur: 180, currency_code: 'USD', attendee_count: 1800, country: 'US', city: 'New York', latitude: 40.7128, longitude: -74.0060, location_label: 'New York, USA', organiser_name: 'Impact America'
    },
    {
      creator_id: creatorId, title: 'Singapore Fintech Festival: DeFi Deep Dive', description: 'A focused side event at SFF week diving deep into decentralised finance, cross-border payments, and regulatory sandboxes across Southeast Asia.', category: 'Finance', tags: ['defi', 'fintech', 'singapore', 'payments', 'asia'], status: 'published', starts_at: d(45, 9), ends_at: d(45, 17), timezone: 'Asia/Singapore', is_online: false, venue_name: 'Marina Bay Sands', venue_address: '10 Bayfront Ave, Singapore 018956', is_paid: true, ticket_price: 350, ticket_price_eur: 305, currency_code: 'SGD', attendee_count: 1200, country: 'SG', city: 'Singapore', latitude: 1.3521, longitude: 103.8198, location_label: 'Singapore', organiser_name: 'DeFi Asia'
    },
    {
      creator_id: creatorId, title: 'Toronto AI Ethics Symposium', description: 'Exploring the ethical dimensions of AI deployment in healthcare, criminal justice, education, and public administration. Featuring researchers from the University of Toronto, Element AI, and the Vector Institute.', category: 'Technology', tags: ['ai', 'ethics', 'toronto', 'policy', 'research'], status: 'published', starts_at: d(50, 9), ends_at: d(50, 17), timezone: 'America/Toronto', is_online: false, venue_name: 'MaRS Discovery District', venue_address: '101 College St, Toronto, ON M5G 1L7', is_paid: false, ticket_price: 0, ticket_price_eur: 0, currency_code: 'CAD', attendee_count: 430, country: 'CA', city: 'Toronto', latitude: 43.6532, longitude: -79.3832, location_label: 'Toronto, Canada', organiser_name: 'AI Ethics Canada'
    },
    {
      creator_id: creatorId, title: 'Sydney Founders Retreat', description: 'A 2-day offsite retreat for 50 founders. Curated sessions on resilience, leadership, fundraising psychology, and scaling culture — with a beautiful harbour setting.', category: 'Business', tags: ['founders', 'retreat', 'sydney', 'leadership'], status: 'published', starts_at: d(55, 9), ends_at: d(56, 16), timezone: 'Australia/Sydney', is_online: false, venue_name: 'Pier One Sydney Harbour', venue_address: '11 Hickson Rd, Walsh Bay NSW 2000', is_paid: true, ticket_price: 890, ticket_price_eur: 540, currency_code: 'AUD', attendee_count: 48, country: 'AU', city: 'Sydney', latitude: -33.8688, longitude: 151.2093, location_label: 'Sydney, Australia', organiser_name: 'Founders Network ANZ'
    },
    {
      creator_id: creatorId, title: 'Nairobi Climate Innovation Bootcamp', description: 'A 3-day intensive program for African climate entrepreneurs. Mentorship from global climate funds, workshops on carbon markets and green finance, and a final pitch to investors.', category: 'Sustainability', tags: ['climate', 'africa', 'innovation', 'nairobi'], status: 'published', starts_at: d(60, 9), ends_at: d(62, 17), timezone: 'Africa/Nairobi', is_online: false, venue_name: 'iHub Nairobi', venue_address: 'Senteu Plaza, Galana Suites, Nairobi', is_paid: false, ticket_price: 0, ticket_price_eur: 0, currency_code: 'KES', attendee_count: 180, country: 'KE', city: 'Nairobi', latitude: -1.2921, longitude: 36.8219, location_label: 'Nairobi, Kenya', organiser_name: 'Climate Hub Africa'
    },
    {
      creator_id: creatorId, title: 'Lisbon E-Commerce Masterclass', description: 'A practical one-day masterclass on building and scaling e-commerce businesses. Shopify, Stripe, logistics, international expansion, and retention marketing — taught by 8-figure e-commerce founders.', category: 'Business', tags: ['ecommerce', 'shopify', 'lisbon', 'retail', 'growth'], status: 'published', starts_at: d(42, 10), ends_at: d(42, 18), timezone: 'Europe/Lisbon', is_online: false, venue_name: 'Web Summit Campus', venue_address: 'Parque das Nacoes, Lisbon', is_paid: true, ticket_price: 120, ticket_price_eur: 120, currency_code: 'EUR', attendee_count: 320, country: 'PT', city: 'Lisbon', latitude: 38.7223, longitude: -9.1393, location_label: 'Lisbon, Portugal', organiser_name: 'Commerce Summit EU'
    },
    {
      creator_id: creatorId, title: 'Warsaw Developer Conference', description: 'Central Europe\'s largest developer conference: 4 tracks covering backend, frontend, DevOps, and security. 80+ talks, workshops, and sponsor booths from top tech companies.', category: 'Technology', tags: ['development', 'backend', 'frontend', 'devops', 'warsaw'], status: 'published', starts_at: d(38, 9), ends_at: d(39, 18), timezone: 'Europe/Warsaw', is_online: false, venue_name: 'Warsaw Expo', venue_address: 'Al. Katowicka 62C, 05-830 Warsaw', is_paid: true, ticket_price: 99, ticket_price_eur: 99, currency_code: 'EUR', attendee_count: 1350, country: 'PL', city: 'Warsaw', latitude: 52.2297, longitude: 21.0122, location_label: 'Warsaw, Poland', organiser_name: 'DevConf EU'
    },
    {
      creator_id: creatorId, title: 'Mumbai Creative Economy Summit', description: "Celebrating India's creative industries — Bollywood, fashion, gaming, music, and digital media. Hear from studios, labels, brands, and creators about the future of the attention economy.", category: 'Business', tags: ['creative', 'india', 'media', 'gaming', 'fashion'], status: 'published', starts_at: d(48, 9), ends_at: d(48, 18), timezone: 'Asia/Kolkata', is_online: false, venue_name: 'Bombay Exhibition Centre', venue_address: 'Goregaon East, Mumbai, Maharashtra 400063', is_paid: true, ticket_price: 3500, ticket_price_eur: 38, currency_code: 'INR', attendee_count: 2200, country: 'IN', city: 'Mumbai', latitude: 19.0760, longitude: 72.8777, location_label: 'Mumbai, India', organiser_name: 'Creative India'
    },
    {
      creator_id: creatorId, title: 'Cape Town EdTech Forum', description: "Exploring technology's role in transforming education across Africa. School technology, adaptive learning platforms, skills training, and youth entrepreneurship. Free to attend.", category: 'Education', tags: ['edtech', 'education', 'africa', 'cape-town'], status: 'published', starts_at: d(52, 9), ends_at: d(52, 17), timezone: 'Africa/Johannesburg', is_online: false, venue_name: 'Cape Town ICC', venue_address: 'Convention Square, 1 Lower Long St, Cape Town', is_paid: false, ticket_price: 0, ticket_price_eur: 0, currency_code: 'ZAR', attendee_count: 540, country: 'ZA', city: 'Cape Town', latitude: -33.9249, longitude: 18.4241, location_label: 'Cape Town, South Africa', organiser_name: 'EdTech Africa'
    },
  ]

  console.log(`Seeding ${events.length} events...`)
  // Insert in batches of 20 to avoid payload limits
  let totalInserted = 0
  const batchSize = 20
  for (let i = 0; i < events.length; i += batchSize) {
    const batch = events.slice(i, i + batchSize)
    const { data, error } = await supabase.from('events').insert(batch).select('id, title')
    if (error) {
      console.error(`Batch ${i / batchSize + 1} failed:`, error)
      process.exit(1)
    }
    totalInserted += data?.length ?? 0
    console.log(`  Batch ${i / batchSize + 1}: inserted ${data?.length} events`)
  }
  console.log(`\n✅ Seeded ${totalInserted} events successfully!`)
}

main().catch(console.error)
