import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  'https://tioqakxnqjxyuzgnwhrb.supabase.co',
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpb3Fha3hucWp4eXV6Z253aHJiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NTUwNzc5OCwiZXhwIjoyMDkxMDgzNzk4fQ.gn5-rMINbSUKJEiNa733DIG8QK68jb7lUg0OPIz8efg',
  { auth: { persistSession: false } }
)

async function main() {
  // Get a valid poster_id
  const { data: profiles, error: profileErr } = await supabase.from('profiles').select('id').limit(1)
  if (profileErr) { console.error('Profile fetch error:', profileErr); process.exit(1) }
  const posterId = profiles?.[0]?.id
  if (!posterId) throw new Error('No profiles found')
  console.log('Using poster_id:', posterId)

  const jobs = [
    // === IRISH TECH JOBS ===
    {
      poster_id: posterId, title: 'Senior Software Engineer (React/TypeScript)', description: 'We are looking for a senior frontend engineer to join our product team in Dublin. You will lead the development of our customer-facing web application, mentor junior engineers, and collaborate closely with product and design. Strong experience with React, TypeScript, and modern state management required.', requirements: '5+ years of frontend experience, React, TypeScript, GraphQL, Jest', job_type: 'full_time', location_type: 'hybrid', location: 'Dublin 2, Ireland', category: 'Tech', tags: ['react', 'typescript', 'frontend', 'graphql', 'senior'], salary_min: 80000, salary_max: 110000, salary_currency: 'EUR', status: 'active', country: 'IE', city: 'Dublin', latitude: 53.3498, longitude: -6.2603, location_label: 'Dublin, Ireland', is_remote: false, salary_min_eur: 80000, salary_max_eur: 110000, currency_code: 'EUR'
    },
    {
      poster_id: posterId, title: 'Backend Engineer (Node.js / AWS)', description: 'Join a fast-growing Irish fintech startup building payment infrastructure. You will design and build scalable microservices, work with Kafka, Redis, and PostgreSQL, and own deployment on AWS. Competitive salary plus equity.', requirements: '4+ years backend experience, Node.js, AWS, PostgreSQL, Docker, Kubernetes', job_type: 'full_time', location_type: 'hybrid', location: 'Cork, Ireland', category: 'Tech', tags: ['node.js', 'aws', 'backend', 'fintech', 'microservices'], salary_min: 70000, salary_max: 95000, salary_currency: 'EUR', status: 'active', country: 'IE', city: 'Cork', latitude: 51.8985, longitude: -8.4756, location_label: 'Cork, Ireland', is_remote: false, salary_min_eur: 70000, salary_max_eur: 95000, currency_code: 'EUR'
    },
    {
      poster_id: posterId, title: 'DevOps Engineer', description: 'We need an experienced DevOps engineer to own our CI/CD pipeline, infrastructure as code, and observability stack. Experience with Terraform, GitHub Actions, and Kubernetes required. Remote-first culture with quarterly in-person meetups in Dublin.', requirements: '3+ years DevOps, Terraform, Kubernetes, Prometheus/Grafana, GitHub Actions', job_type: 'full_time', location_type: 'remote', location: 'Ireland (remote)', category: 'DevOps', tags: ['devops', 'kubernetes', 'terraform', 'ci-cd', 'aws'], salary_min: 75000, salary_max: 100000, salary_currency: 'EUR', status: 'active', country: 'IE', city: 'Dublin', latitude: 53.3498, longitude: -6.2603, location_label: 'Remote — Ireland', is_remote: true, salary_min_eur: 75000, salary_max_eur: 100000, currency_code: 'EUR'
    },
    {
      poster_id: posterId, title: 'Product Designer (UX/UI)', description: 'Our Dublin-based product team is looking for a mid-to-senior product designer to own the end-to-end design of our mobile and web apps. You will run user research sessions, build prototypes in Figma, and work directly with engineering to ship delightful products.', requirements: '3+ years product design, Figma, Prototyping, User research, Design systems', job_type: 'full_time', location_type: 'hybrid', location: 'Dublin, Ireland', category: 'Design', tags: ['ux', 'ui', 'figma', 'product-design', 'mobile'], salary_min: 65000, salary_max: 85000, salary_currency: 'EUR', status: 'active', country: 'IE', city: 'Dublin', latitude: 53.3498, longitude: -6.2603, location_label: 'Dublin, Ireland', is_remote: false, salary_min_eur: 65000, salary_max_eur: 85000, currency_code: 'EUR'
    },
    {
      poster_id: posterId, title: 'Data Scientist (ML / Python)', description: 'Join a Limerick-based SaaS company using machine learning to transform supply chain management. You will build and deploy predictive models, work with large datasets, and present insights to executive stakeholders.', requirements: 'PhD or MSc in relevant field, Python, sklearn, PyTorch, SQL, data visualisation', job_type: 'full_time', location_type: 'hybrid', location: 'Limerick, Ireland', category: 'Data', tags: ['data-science', 'machine-learning', 'python', 'pytorch', 'sql'], salary_min: 70000, salary_max: 95000, salary_currency: 'EUR', status: 'active', country: 'IE', city: 'Limerick', latitude: 52.6638, longitude: -8.6267, location_label: 'Limerick, Ireland', is_remote: false, salary_min_eur: 70000, salary_max_eur: 95000, currency_code: 'EUR'
    },
    {
      poster_id: posterId, title: 'Growth Marketing Manager', description: 'A fast-growing Irish D2C brand is hiring a Growth Marketing Manager to own paid media, SEO, email marketing, and conversion optimisation. Experience with Meta Ads, Google Ads, and Klaviyo preferred. Full-time, Dublin.', requirements: '4+ years growth marketing, Meta Ads, Google Ads, Klaviyo, CRO, analytics', job_type: 'full_time', location_type: 'on_site', location: 'Dublin 1, Ireland', category: 'Marketing', tags: ['growth', 'paid-media', 'seo', 'email-marketing', 'cro'], salary_min: 55000, salary_max: 75000, salary_currency: 'EUR', status: 'active', country: 'IE', city: 'Dublin', latitude: 53.3498, longitude: -6.2603, location_label: 'Dublin, Ireland', is_remote: false, salary_min_eur: 55000, salary_max_eur: 75000, currency_code: 'EUR'
    },
    {
      poster_id: posterId, title: 'Sales Development Representative (SaaS)', description: 'Join an Irish B2B SaaS startup as an SDR. You will prospect and qualify leads, run outbound email and LinkedIn campaigns, and book demo calls for the account executive team. Excellent commission structure.', requirements: '1-2 years SDR experience, Salesforce/HubSpot, cold outreach, SaaS industry knowledge', job_type: 'full_time', location_type: 'hybrid', location: 'Dublin, Ireland', category: 'Sales', tags: ['sdr', 'saas', 'b2b', 'outbound', 'salesforce'], salary_min: 40000, salary_max: 55000, salary_currency: 'EUR', status: 'active', country: 'IE', city: 'Dublin', latitude: 53.3498, longitude: -6.2603, location_label: 'Dublin, Ireland', is_remote: false, salary_min_eur: 40000, salary_max_eur: 55000, currency_code: 'EUR'
    },
    {
      poster_id: posterId, title: 'AI/ML Engineer', description: 'Work on cutting-edge AI products at a Series A Dublin startup. You will fine-tune LLMs, build RAG pipelines, and ship production AI features used by thousands of customers. Strong Python and MLOps experience required.', requirements: '3+ years ML engineering, Python, LLMs, RAG, vector databases, MLflow', job_type: 'full_time', location_type: 'hybrid', location: 'Dublin 4, Ireland', category: 'AI', tags: ['ai', 'ml', 'llm', 'rag', 'python'], salary_min: 85000, salary_max: 120000, salary_currency: 'EUR', status: 'active', country: 'IE', city: 'Dublin', latitude: 53.3388, longitude: -6.2380, location_label: 'Dublin 4, Ireland', is_remote: false, salary_min_eur: 85000, salary_max_eur: 120000, currency_code: 'EUR'
    },
    {
      poster_id: posterId, title: 'Financial Analyst (FP&A)', description: 'A leading Irish professional services firm is seeking an FP&A Analyst to support budgeting, forecasting, and strategic planning processes. Strong Excel modelling skills and experience with ERP systems required. Cork or Dublin based.', requirements: 'ACA/ACCA qualified, 3+ years FP&A, Excel, financial modelling, ERP experience', job_type: 'full_time', location_type: 'hybrid', location: 'Cork, Ireland', category: 'Finance', tags: ['finance', 'fpa', 'accounting', 'modelling', 'aca'], salary_min: 55000, salary_max: 75000, salary_currency: 'EUR', status: 'active', country: 'IE', city: 'Cork', latitude: 51.8985, longitude: -8.4756, location_label: 'Cork, Ireland', is_remote: false, salary_min_eur: 55000, salary_max_eur: 75000, currency_code: 'EUR'
    },
    {
      poster_id: posterId, title: 'Full Stack Developer (Next.js / Supabase) — Contract', description: 'A 6-month contract opportunity with an Irish startup building a community marketplace. You will work across the full stack with Next.js 14, Supabase, TypeScript, and Tailwind CSS. Flexible remote working.', requirements: '4+ years full stack, Next.js, Supabase/PostgreSQL, TypeScript, Tailwind', job_type: 'contract', location_type: 'remote', location: 'Ireland (remote)', category: 'Tech', tags: ['nextjs', 'supabase', 'typescript', 'full-stack', 'contract'], salary_min: 500, salary_max: 700, salary_currency: 'EUR', status: 'active', country: 'IE', city: 'Dublin', latitude: 53.3498, longitude: -6.2603, location_label: 'Remote — Ireland', is_remote: true, salary_min_eur: 500, salary_max_eur: 700, currency_code: 'EUR'
    },
    {
      poster_id: posterId, title: 'Community Manager', description: 'FreeTrust is looking for a Community Manager to grow and engage our member base across Ireland and beyond. You will run events, manage social media, create content, and be the voice of our community. Passion for the creator economy and community building essential.', requirements: '2+ years community management, social media, content creation, event coordination', job_type: 'full_time', location_type: 'hybrid', location: 'Dublin, Ireland', category: 'Marketing', tags: ['community', 'social-media', 'content', 'events', 'creator-economy'], salary_min: 42000, salary_max: 55000, salary_currency: 'EUR', status: 'active', country: 'IE', city: 'Dublin', latitude: 53.3498, longitude: -6.2603, location_label: 'Dublin, Ireland', is_remote: false, salary_min_eur: 42000, salary_max_eur: 55000, currency_code: 'EUR'
    },
    {
      poster_id: posterId, title: 'iOS Developer (Swift)', description: 'Join our mobile team at a Galway-based healthtech company building apps used by 200k+ patients. You will own major features from design to App Store release, working closely with a small, talented team.', requirements: '3+ years Swift, SwiftUI, Combine, App Store deployment, healthcare experience a plus', job_type: 'full_time', location_type: 'hybrid', location: 'Galway, Ireland', category: 'Tech', tags: ['ios', 'swift', 'swiftui', 'mobile', 'healthtech'], salary_min: 70000, salary_max: 95000, salary_currency: 'EUR', status: 'active', country: 'IE', city: 'Galway', latitude: 53.2707, longitude: -9.0568, location_label: 'Galway, Ireland', is_remote: false, salary_min_eur: 70000, salary_max_eur: 95000, currency_code: 'EUR'
    },
    {
      poster_id: posterId, title: 'Graphic Designer (Part Time)', description: 'A boutique Dublin branding agency is hiring a part-time graphic designer to support client projects — brand identity, packaging, print, and digital assets. Adobe Creative Suite expertise essential. 3 days per week, flexible hours.', requirements: '2+ years graphic design, Illustrator, Photoshop, InDesign, branding experience', job_type: 'part_time', location_type: 'hybrid', location: 'Dublin, Ireland', category: 'Design', tags: ['graphic-design', 'branding', 'adobe', 'illustration', 'part-time'], salary_min: 28000, salary_max: 38000, salary_currency: 'EUR', status: 'active', country: 'IE', city: 'Dublin', latitude: 53.3498, longitude: -6.2603, location_label: 'Dublin, Ireland', is_remote: false, salary_min_eur: 28000, salary_max_eur: 38000, currency_code: 'EUR'
    },
    {
      poster_id: posterId, title: 'Account Executive (Enterprise SaaS)', description: 'A well-funded Irish SaaS company is expanding its enterprise sales team. You will manage a territory of mid-market and enterprise accounts, run complex sales cycles, and close 6-figure deals. Strong negotiation and stakeholder management skills required.', requirements: '5+ years enterprise SaaS sales, Salesforce, complex deal management, £500k+ AE quota', job_type: 'full_time', location_type: 'hybrid', location: 'Dublin, Ireland', category: 'Sales', tags: ['enterprise-sales', 'saas', 'account-executive', 'b2b', 'crm'], salary_min: 75000, salary_max: 100000, salary_currency: 'EUR', status: 'active', country: 'IE', city: 'Dublin', latitude: 53.3498, longitude: -6.2603, location_label: 'Dublin, Ireland', is_remote: false, salary_min_eur: 75000, salary_max_eur: 100000, currency_code: 'EUR'
    },
    {
      poster_id: posterId, title: 'Freelance Content Strategist', description: 'A digital marketing agency is looking for a freelance content strategist to develop content plans, editorial calendars, and SEO strategies for clients in fintech, ecommerce, and SaaS. Remote, flexible hours, ongoing work.', requirements: '3+ years content strategy, SEO, editorial calendar management, fintech or SaaS experience preferred', job_type: 'freelance', location_type: 'remote', location: 'Remote', category: 'Marketing', tags: ['content-strategy', 'seo', 'copywriting', 'freelance', 'fintech'], salary_min: 400, salary_max: 600, salary_currency: 'EUR', status: 'active', country: 'IE', city: null, latitude: null, longitude: null, location_label: 'Remote', is_remote: true, salary_min_eur: 400, salary_max_eur: 600, currency_code: 'EUR'
    },

    // === GLOBAL / REMOTE JOBS ===
    {
      poster_id: posterId, title: 'Principal Engineer (Platform)', description: 'A Series B London-based infrastructure startup is hiring a Principal Engineer to lead the design and build of their developer platform. Distributed systems, cloud-native architecture, and technical leadership experience required. Remote-first globally.', requirements: '10+ years software engineering, distributed systems, Kubernetes, platform engineering, technical leadership', job_type: 'full_time', location_type: 'remote', location: 'Remote (global)', category: 'Tech', tags: ['platform-engineering', 'distributed-systems', 'kubernetes', 'principal', 'remote'], salary_min: 150000, salary_max: 200000, salary_currency: 'GBP', status: 'active', country: 'GB', city: 'London', latitude: 51.5074, longitude: -0.1278, location_label: 'Remote — Global (London HQ)', is_remote: true, salary_min_eur: 175000, salary_max_eur: 235000, currency_code: 'GBP'
    },
    {
      poster_id: posterId, title: 'Senior Product Manager (Consumer App)', description: 'A Berlin-based consumer app with 5M+ users is looking for a Senior PM to own their growth and engagement product surface. You will define strategy, run experiments, and work with a team of engineers and designers.', requirements: '5+ years product management, consumer apps, A/B testing, growth metrics, roadmap ownership', job_type: 'full_time', location_type: 'hybrid', location: 'Berlin, Germany', category: 'Product', tags: ['product-management', 'consumer', 'growth', 'berlin', 'mobile'], salary_min: 90000, salary_max: 120000, salary_currency: 'EUR', status: 'active', country: 'DE', city: 'Berlin', latitude: 52.5200, longitude: 13.4050, location_label: 'Berlin, Germany', is_remote: false, salary_min_eur: 90000, salary_max_eur: 120000, currency_code: 'EUR'
    },
    {
      poster_id: posterId, title: 'Marketing Lead (EMEA)', description: 'A US-headquartered SaaS company expanding into Europe needs a Marketing Lead to build and run EMEA marketing: demand generation, events, partnerships, and localisation. Based in Amsterdam or remote across EMEA.', requirements: '6+ years B2B marketing, EMEA experience, demand gen, content, events, HubSpot', job_type: 'full_time', location_type: 'remote', location: 'Remote — EMEA', category: 'Marketing', tags: ['marketing', 'emea', 'demand-gen', 'b2b', 'remote'], salary_min: 80000, salary_max: 110000, salary_currency: 'EUR', status: 'active', country: 'NL', city: 'Amsterdam', latitude: 52.3676, longitude: 4.9041, location_label: 'Remote — EMEA (Amsterdam hub)', is_remote: true, salary_min_eur: 80000, salary_max_eur: 110000, currency_code: 'EUR'
    },
    {
      poster_id: posterId, title: 'Senior Data Engineer (dbt / Snowflake)', description: 'A fintech scale-up with operations across Europe and North America is hiring a Senior Data Engineer to build and maintain their modern data stack. Experience with dbt, Snowflake, Airflow, and Python required.', requirements: '4+ years data engineering, dbt, Snowflake, Airflow, Python, SQL', job_type: 'full_time', location_type: 'remote', location: 'Remote (Europe)', category: 'Data', tags: ['data-engineering', 'dbt', 'snowflake', 'airflow', 'python'], salary_min: 85000, salary_max: 115000, salary_currency: 'EUR', status: 'active', country: null, city: null, latitude: null, longitude: null, location_label: 'Remote — Europe', is_remote: true, salary_min_eur: 85000, salary_max_eur: 115000, currency_code: 'EUR'
    },
    {
      poster_id: posterId, title: 'UX Designer — Fintech (Freelance)', description: 'An international fintech startup is seeking a freelance UX designer for a 3-month project to redesign their onboarding and KYC flow. Remote, flexible, great portfolio opportunity.', requirements: 'Proven UX design experience, Figma, fintech or financial product experience preferred, portfolio required', job_type: 'freelance', location_type: 'remote', location: 'Remote (global)', category: 'Design', tags: ['ux', 'fintech', 'figma', 'freelance', 'onboarding'], salary_min: 450, salary_max: 700, salary_currency: 'EUR', status: 'active', country: null, city: null, latitude: null, longitude: null, location_label: 'Remote — Global', is_remote: true, salary_min_eur: 450, salary_max_eur: 700, currency_code: 'EUR'
    },
    {
      poster_id: posterId, title: 'AI Research Engineer', description: 'Join the research team at a Paris-based AI lab working on foundation models for scientific discovery. You will implement novel architectures, run large-scale training runs, and publish at top ML conferences.', requirements: 'PhD in ML/CS or equivalent experience, PyTorch, distributed training, research publications a plus', job_type: 'full_time', location_type: 'on_site', location: 'Paris, France', category: 'AI', tags: ['ai-research', 'pytorch', 'foundation-models', 'phd', 'paris'], salary_min: 90000, salary_max: 140000, salary_currency: 'EUR', status: 'active', country: 'FR', city: 'Paris', latitude: 48.8566, longitude: 2.3522, location_label: 'Paris, France', is_remote: false, salary_min_eur: 90000, salary_max_eur: 140000, currency_code: 'EUR'
    },
    {
      poster_id: posterId, title: 'Finance Manager (Startup)', description: 'A fast-growing Barcelona startup is looking for a hands-on Finance Manager to own monthly close, financial reporting, budgeting, and investor relations. ACCA/CPA qualification and startup experience preferred.', requirements: 'ACCA/CPA qualified, 5+ years finance, startup experience, Excel, financial reporting', job_type: 'full_time', location_type: 'on_site', location: 'Barcelona, Spain', category: 'Finance', tags: ['finance', 'accounting', 'acca', 'startup', 'barcelona'], salary_min: 60000, salary_max: 80000, salary_currency: 'EUR', status: 'active', country: 'ES', city: 'Barcelona', latitude: 41.3851, longitude: 2.1734, location_label: 'Barcelona, Spain', is_remote: false, salary_min_eur: 60000, salary_max_eur: 80000, currency_code: 'EUR'
    },
    {
      poster_id: posterId, title: 'Senior iOS Engineer (SwiftUI)', description: 'A healthcare technology company based in Toronto is looking for a Senior iOS Engineer to build their next-generation patient app. SwiftUI, HealthKit, and a track record of shipping to the App Store required.', requirements: '5+ years iOS development, SwiftUI, HealthKit, App Store, agile team experience', job_type: 'full_time', location_type: 'remote', location: 'Remote — North America', category: 'Tech', tags: ['ios', 'swiftui', 'healthkit', 'canada', 'healthtech'], salary_min: 120000, salary_max: 160000, salary_currency: 'CAD', status: 'active', country: 'CA', city: 'Toronto', latitude: 43.6532, longitude: -79.3832, location_label: 'Remote — Canada (Toronto HQ)', is_remote: true, salary_min_eur: 82000, salary_max_eur: 110000, currency_code: 'CAD'
    },
    {
      poster_id: posterId, title: 'Content Marketing Manager (Remote)', description: 'A global EdTech company is hiring a Content Marketing Manager to build their content engine: blog posts, whitepapers, case studies, SEO, and social media. Remote-first, flexible working hours.', requirements: '4+ years content marketing, SEO, CMS management, edtech or b2b saas preferred', job_type: 'full_time', location_type: 'remote', location: 'Remote (worldwide)', category: 'Marketing', tags: ['content-marketing', 'seo', 'blog', 'edtech', 'remote'], salary_min: 50000, salary_max: 70000, salary_currency: 'EUR', status: 'active', country: null, city: null, latitude: null, longitude: null, location_label: 'Remote — Worldwide', is_remote: true, salary_min_eur: 50000, salary_max_eur: 70000, currency_code: 'EUR'
    },
    {
      poster_id: posterId, title: 'Enterprise Account Executive (EMEA)', description: 'A US enterprise software company expanding in EMEA is looking for an experienced Account Executive to carry a €1.5M quota. You will sell to Fortune 500 companies across the UK, Ireland, and Europe.', requirements: '5+ years enterprise SaaS AE, EMEA experience, C-suite selling, Salesforce, €1M+ quota', job_type: 'full_time', location_type: 'remote', location: 'Remote — UK/Ireland', category: 'Sales', tags: ['enterprise', 'sales', 'emea', 'saas', 'account-executive'], salary_min: 100000, salary_max: 140000, salary_currency: 'EUR', status: 'active', country: 'GB', city: 'London', latitude: 51.5074, longitude: -0.1278, location_label: 'Remote — UK/Ireland', is_remote: true, salary_min_eur: 100000, salary_max_eur: 140000, currency_code: 'EUR'
    },
    {
      poster_id: posterId, title: 'Rust Engineer (Systems / Networking)', description: 'A distributed computing startup in Lisbon is hiring a Rust engineer to build high-performance networking components for their edge computing platform. Strong systems programming background required.', requirements: '3+ years Rust, networking protocols, low-latency systems, Linux internals', job_type: 'full_time', location_type: 'on_site', location: 'Lisbon, Portugal', category: 'Tech', tags: ['rust', 'systems', 'networking', 'edge-computing', 'lisbon'], salary_min: 80000, salary_max: 110000, salary_currency: 'EUR', status: 'active', country: 'PT', city: 'Lisbon', latitude: 38.7223, longitude: -9.1393, location_label: 'Lisbon, Portugal', is_remote: false, salary_min_eur: 80000, salary_max_eur: 110000, currency_code: 'EUR'
    },
    {
      poster_id: posterId, title: 'Blockchain Developer (Solidity / Web3)', description: 'A DeFi protocol building on Ethereum is looking for a Solidity developer to write and audit smart contracts. Experience with Hardhat, OpenZeppelin, and on-chain security best practices essential.', requirements: '3+ years Solidity, EVM, Hardhat, OpenZeppelin, DeFi protocols, security audits', job_type: 'contract', location_type: 'remote', location: 'Remote (global)', category: 'Tech', tags: ['solidity', 'web3', 'defi', 'ethereum', 'smart-contracts'], salary_min: 600, salary_max: 900, salary_currency: 'EUR', status: 'active', country: null, city: null, latitude: null, longitude: null, location_label: 'Remote — Global', is_remote: true, salary_min_eur: 600, salary_max_eur: 900, currency_code: 'EUR'
    },
    {
      poster_id: posterId, title: 'Visual Designer (Brand & Social)', description: 'A lifestyle brand growing fast across Europe needs a Visual Designer to create social media content, brand campaigns, product imagery, and packaging design. Based in Dublin, hybrid working.', requirements: '2-4 years visual design, social media content, Figma, Photoshop, brand identity', job_type: 'full_time', location_type: 'hybrid', location: 'Dublin, Ireland', category: 'Design', tags: ['visual-design', 'brand', 'social-media', 'figma', 'packaging'], salary_min: 42000, salary_max: 55000, salary_currency: 'EUR', status: 'active', country: 'IE', city: 'Dublin', latitude: 53.3498, longitude: -6.2603, location_label: 'Dublin, Ireland', is_remote: false, salary_min_eur: 42000, salary_max_eur: 55000, currency_code: 'EUR'
    },
    {
      poster_id: posterId, title: 'Head of Data (Analytics & BI)', description: 'An Irish retail group is hiring a Head of Data to build and lead a 5-person data team. You will define the data strategy, oversee the data warehouse, and deliver insights that drive commercial decisions.', requirements: '8+ years data, team leadership, BI tools (Looker/Tableau), SQL, strategic stakeholder management', job_type: 'full_time', location_type: 'hybrid', location: 'Dublin, Ireland', category: 'Data', tags: ['data-leadership', 'analytics', 'bi', 'looker', 'sql'], salary_min: 100000, salary_max: 130000, salary_currency: 'EUR', status: 'active', country: 'IE', city: 'Dublin', latitude: 53.3498, longitude: -6.2603, location_label: 'Dublin, Ireland', is_remote: false, salary_min_eur: 100000, salary_max_eur: 130000, currency_code: 'EUR'
    },
  ]

  console.log(`Seeding ${jobs.length} jobs...`)
  let totalInserted = 0
  const batchSize = 15
  for (let i = 0; i < jobs.length; i += batchSize) {
    const batch = jobs.slice(i, i + batchSize)
    const { data, error } = await supabase.from('jobs').insert(batch).select('id, title')
    if (error) {
      console.error(`Batch ${i / batchSize + 1} failed:`, error)
      process.exit(1)
    }
    totalInserted += data?.length ?? 0
    console.log(`  Batch ${i / batchSize + 1}: inserted ${data?.length} jobs`)
  }
  console.log(`\n✅ Seeded ${totalInserted} jobs successfully!`)
}

main().catch(console.error)
